# Generated by Django 5.1.7 on 2025-03-19 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Client's first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Client's last name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for confirmations and notifications",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Client's date of birth for health records"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Any relevant medical conditions or health concerns",
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Any allergies to herbs, medicines, or other substances",
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True,
                        help_text="Current medications, supplements, or herbal remedies being taken",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the client record was created",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Link to user account for online access",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
